mentor/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView, DeleteView, DetailView

from mentor.views import *

urlpatterns = [
    url(r'^register/$', register),
    url(r'^$', RedirectView.as_view(url='teams/', permanent=True), name='index'),
    url(r'^teams', teams_list),
    # candidate/id is friendly to server cache
    url(r'^candidate/(?P<candidate_id>[0-9]+)$', candidate_detail),
]

voice/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^accounts/', include(admin.site.urls)),
    url(r'^', include('mentor.urls', namespace='c')),
]

mentor/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.contrib.auth.models import User
from django.db import models


class Mentor(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    # name could be duplicated, but mobile should be unique
    mobile = models.CharField(max_length=20, null=True, unique=True)
    detail = models.TextField(null=True)

    def __unicode__(self):
        return 'Mentor ' + self.user.username

    class Meta:
        permissions = (
            ("voice_admin", "Administrator for Voice"),
            ("voice_mentor", "Mentor for Voice"),
        )


class Team(models.Model):
    name = models.CharField(max_length=20)
    mentor = models.ForeignKey(Mentor, null=True, blank=True)
    average_score = models.FloatField(default=0)

    def __unicode__(self):
        return 'Team ' + self.name


class Candidate(models.Model):
    name = models.CharField(max_length=20)
    # name could be duplicated, but mobile should be unique
    mobile = models.CharField(max_length=20, null=True, unique=True)
    team = models.ForeignKey(Team)
    average_score = models.FloatField(default=0)

    def __unicode__(self):
        return 'Candidate ' + self.name


class Activity(models.Model):
    candidate = models.ForeignKey(Candidate)
    song = models.CharField(max_length=30, null=True)
    perform_date = models.DateField(auto_now_add=True)
    average_score = models.FloatField(default=0)

    def __unicode__(self):
        return 'Activity of ' + self.candidate.name + " on " + str(self.perform_date) + ", score " + str(self.average_score)


class ActivityDetail(models.Model):
    activity = models.ForeignKey(Activity)
    mentor = models.ForeignKey(Mentor)
    score = models.PositiveIntegerField(default=0)

    def __unicode__(self):
        return 'Activity of ' + self.activity.candidate.name + " on " + str(self.activity.perform_date) + ", score " + str(self.score)

mentor/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

from mentor.models import *


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            return HttpResponseRedirect("/")
    else:
        form = UserCreationForm()

    context = {'form': form}
    return render(request, 'registration/register.html', context)


def teams_list(request):
    user = request.user
    if user.has_perm('mentor.voice_admin'):
        teams = Team.objects.all()
    else:
        mentor = Mentor.objects.get(user=user)
        teams = Team.objects.filter(mentor=mentor)

    context = {'user': user,
               'team_list': teams}
    return render(request, 'mentor/team_list.html', context)


def candidate_detail(request, candidate_id):
    candidate = get_object_or_404(Candidate, pk=candidate_id)

    user = request.user
    if not user.is_superuser:
        mentor = Mentor.objects.get(user=user)
        if candidate.team.mentor != mentor:
            raise PermissionDenied

    mentors = Mentor.objects.all()
    context = {'user': user,
               'candidate': candidate,
               'mentors': mentors}
    return render(request, 'mentor/candidate.html', context)

mentor/templates/mentor/base.html
<!DOCTYPE html>
<html lang="zh">
<head>
    {% load staticfiles %}

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="shortcut icon" type="image/png" href="{% static 'image/fire-ball_32.png' %}"/>
    <link rel="apple-touch-icon" href="{% static 'image/fire-ball_64.png' %}">

{#    <link rel="stylesheet" href="{% static 'css/style.css' %}">#}

    {#jquery#}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

    {#bootstrap#}
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    {#jquery ui#}
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>

{#    <script src="{% static 'js/confirm.js' %}"></script>#}

    {% block head %}{% endblock %}

    <title>The Voice System</title>
</head>

<body>
<div style="display:none;" ><img src="{% static 'image/fire-ball_256.png' %}" /></div>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Voice</a>
            <span></span>
        </div>


        <div class="collapse navbar-collapse" id="myNavbar">
{#            <ul class="nav navbar-nav">#}
{#                <li><a href="/employees">小弟</a></li>#}
{#                <li><a href="/customers">客户</a></li>#}
{#            </ul>#}
            <p class="navbar-text">Welcome, {{ user.username }}</p>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="/accounts/">Administrator</a></li>
                <li><a href="/accounts/logout">Logout</a></li>
            </ul>
        </div>
    </div>
</nav>

<div id="content" class="container">
    {% block content %}{% endblock %}
</div>

</body>
</html>

mentor/templates/mentor/candidate.html
{% extends "mentor/base.html" %}{% block content %}    <div class="well">Candidate Name: {{ candidate.name }}<br>Average Score: {{ candidate.average_score }}</div>    <table class="table table-striped">        <tr>            <th>Date</th>            <th>Song</th>            <th>Score</th>            {% for mentor in mentors %}                <th></th>            {% endfor %}        </tr>        {% for activity in candidate.activity_set.all %}            <tr>                <td>{{ activity.perform_date }}</td>                <td>{{ activity.song }}</td>                <td>{{ activity.average_score|floatformat:2 }}</td>                {% for activity_detail in activity.activitydetail_set.all %}                    <td>{{ activity_detail.mentor.user.username }}/{{ activity_detail.score }}</td>                {% endfor %}            </tr>        {% endfor %}    </table>{% endblock %}

mentor/templates/mentor/team_list.html
{% extends "mentor/base.html" %}{% block content %}    <table class="table table-condensed">        <tr>            <th>Name</th>            <th>Score</th>        </tr>        {% for team in team_list %}            <tr class="info">                <td>                    <span class="glyphicon glyphicon-plus"></span>                    {{ team.name }}  ( {{ team.mentor.user.username }}  )                </td>                <td>{{ team.average_score|floatformat:2  }}</td>            </tr>            {% for candidate in team.candidate_set.all %}            <tr class="success">                <td>                    <span class="glyphicon glyphicon-minus"></span>                    <a href="/candidate/{{ candidate.id }}"> {{ candidate.name }} </a>                </td>                <td>{{ candidate.average_score|floatformat:2  }}</td>            </tr>            {% endfor %}        {% endfor %}    </table>{% endblock %}